config/routes.rb
Rails.application.routes.draw do
  get 'user_dashboard/index'
  get 'adm_dashboard/index'

  post 'usuarios/encontrar'
  get 'usuarios/encontrar'

  post 'welcome/redirecionarusuario'
  
  get 'caronas/encontrarcaronas'
  post 'usuarios/toogleusuario'

  resources :campus
  resources :usuarios
  resources :caronas


  resources :caronas do
    member do
      get :encontrarcaronas
    end
  end
  
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/campu.rb
class Campu < ApplicationRecord
    validates_length_of :nome, within: 7..25, presence: true,message: "numero de caracteres invalido"

    validates_length_of :endereco, within: 15..100, presence: true, message: "numero de caracteres invalido"

    validates_length_of :bairro, minimum: 2, message: "numero de abaixo do permitido "

    validates_length_of :cidade, minimum: 2, message: "numero de abaixo do  permitdo"


    validates_length_of :cep, is: 8, presence: true, message: "deve possuir 8 caracteres"
end

app/controllers/campus_controller.rb
class CampusController < ApplicationController
  authenticate_with_iduff_keycloak
  load_and_authorize_resource
  before_action :set_campu, only: %i[ show edit update destroy ]

  # GET /campus or /campus.json
  def index
    @campus = Campu.all
  end

  # GET /campus/1 or /campus/1.json
  def show
  end

  # GET /campus/new
  def new
    @campu = Campu.new
    @lista_cidades = Pub::Cidade.where("estado_id = '18'").all
      
  end

  # GET /campus/1/edit
  def edit
    @lista_cidades = Pub::Cidade.where("estado_id = '18'").all
  end

  # POST /campus or /campus.json
  def create
    @lista_cidades = Pub::Cidade.where("estado_id = '18'").all
    @campu = Campu.new(campu_params)

    respond_to do |format|
      if @campu.save
        format.html { redirect_to campu_url(@campu), notice: "Campu was successfully created." }
        format.json { render :show, status: :created, location: @campu }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @campu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campus/1 or /campus/1.json
  def update
    respond_to do |format|
      if @campu.update(campu_params)
        format.html { redirect_to campu_url(@campu), notice: "Campu was successfully updated." }
        format.json { render :show, status: :ok, location: @campu }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @campu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campus/1 or /campus/1.json
  def destroy
    @campu.destroy

    respond_to do |format|
      format.html { redirect_to campus_url, notice: "Campu was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campu
      @campu = Campu.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def campu_params
      params.require(:campu).permit(:nome, :endereco, :numero, :bairro, :cidade, :cep)
    end

    
  end  

app/helpers/campus_helper.rb
module CampusHelper
    
    #Criar lista de listas do modelo Pub::Cidade para criar option do select
    def criar_options (modelo_lista)
        lista_option = []
        modelo_lista.each do |obj|
            lista_option << [obj.nome, obj.nome]
        end
        return lista_option
    end

    def cep_mask(atributo)
        "#{atributo[0..4]}-#{atributo[5..7]}"
    end
end

app/views/campus/_form.html.erb
<%= form_with(model: campu, local: true, class:"p-3") do |form| %>
  <% if campu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(campu.errors.count, "error") %> prohibited this campu from being saved:</h2>

      <ul>
        <% campu.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group p-2">
    <%= form.label "Nome:", class:"form-label h5" %>
    <%= form.text_field :nome,class:"form-control h5" %>
  </div>
  

  <div class="form-group p-2">
    <%= form.label "Endereço:", class:"col-sm-1 h5 form-label" %>
    <%= form.text_field :endereco, class:"form-control h5" %>
  </div>

  <div class="form-group p-2 row g-3">
    <div class="col-md-6">
      <%= form.label "Número:", class:"form-label h5" %>
      <%= form.text_field :numero, class:"form-control h5" %>
    </div>
    <div class="col-md-6">
      <%= form.label "Bairro:", class:"form-label h5" %>
      <%= form.text_field :bairro, class:"form-control h5" %>
    </div>

    <div class="col-md-6">
      <%= form.label "Cidade:", class:"form-label h5" %>
      <%= form.select(:cidade, @lista_cidades.collect{|cidade|[cidade.nome, cidade.nome]},{}, {:class => "form-select"})%>
    </div>  

    <div class="col-md-6">
      <%= form.label "CEP:",class:"form-label h5"%>
      <%= form.text_field :cep, class:"cep form-control"%>
    </div>

    
  </div>
  
<% end %>

app/views/campus/edit.html.erb
<h1 class="py-2">Editar Campus</h1>

<%= render 'form', campu: @campu %>

<%= link_to 'Mostrar', @campu, class:"btn btn-primary" %> |
<%= link_to 'Voltar', campus_path, class:"btn btn-primary"%>

app/views/campus/index.html.erb
<main class="d-flex sidebar justify-content-between">
<%= render "partials/sidebar" %>
<section class="conatiner m-3 w-75">
  <p id="notice"><%= notice %></p>
  <div class="d-flex justify-content-between align-items-center">
    <h1>Campus</h1>
    <%= link_to 'Cadastrar novo Campus', new_campu_path, class: "btn btn btn-success text-light" %>
  </div>

  <table class="table table-striped">
  <thead>
  <tr>
    <th scope="col" class="h5 p-3 text-center">#</th>
    <th scope="col" class="h5 p-3 text-center">Nome</th>
    <th scope="col" class="h5 p-3 text-center">Endereco</th>
    <th scope="col" class="h5 p-3 text-center">Cidade</th>
    <th scope="col" class="h5 p-3 text-center">Cep</th>
    <th scope="col" class="h5 p-3 text-center" colspan="3">Opções</th>
  </tr>
  </thead>

  <tbody>
  <% @campus.each do |campu| %>
    <tr>
      <td class="text-center"><%= campu.id %></td>
      <td class="text-center"><%= campu.nome %></td>
      <td class="text-center"><%= campu.endereco %>, <%= campu.numero %>, <%= campu.bairro %></td>
      <td class="text-center"><%= campu.cidade %></td>
      <td class="text-center"><%= cep_mask(campu.cep) %></td>
      <td class="text-center"><%= link_to 'Campus', campu, class:"btn btn-primary text-light" %></td>
      <td class="text-center"><%= link_to 'Editar', edit_campu_path(campu),  class:"btn btn-warning text-light" %></td>
      <td class="text-center"><%= link_to 'Apagar', campu, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger text-light" %></td>
    </tr>
  <% end %>
  </tbody>
  </table>

  <br>



</section>

app/views/campus/new.html.erb
<section class="p-2" title="Retornar para <%= campus_path%>">
    <main class="p-2">
        <h1 class="p-2">Cadastrar Novo Campus</h1>
        <%= render 'form', campu: @campu %>
        <div class="form-group mt-3 d-flex justify-content-center py-5">
            <%= form.submit "Cadastrar Campus", class:"btn btn-primary mx-2 w-75" %>
        </div>
    </main>
</section>

app/views/campus/show.html.erb
<p id="notice"><%= notice %></p>
<main class="d-flex sidebar justify-content-between">
  <%= render "partials/sidebar" %>

  <section class="m-3 w-75 container">
      <div class="row mb-5 px-2">
        <%= image_tag "campos_foto", class:"w-50"%>

        <div class="col">
          <h5 class="py-2"><strong>Nome:</strong> <%= @campu.nome%></h5>
          <h5 class="py-2"><strong>Endereço:</strong> <%= @campu.endereco%></h5>
          <h5 class="py-2"><strong>Bairro:</strong> <%= @campu.bairro%></h5>
          <h5 class="py-2"><strong>Número:</strong> <%= @campu.numero%></h5>
          <h5 class="py-2"><strong>Cidade:</strong> <%= @campu.cidade%></h5>
          <h5 class="py-2"><strong>CEP:</strong> <%= @campu.cep[0..4]+"-"+@campu.cep[5..7]%></h5>
        </div>
      </div>
      <div class="col d-flex justify-content-center">
        <%= link_to 'Editar Campus', edit_campu_path(@campu), class: "btn btn-warning text-light m-2" %>
        <%= link_to 'Retornar', campus_path, class:"btn btn-info text-light m-2" %>
      </div>
 
  </section>
</main>