config/routes.rb
Rails.application.routes.draw do
  get 'user_dashboard/index'
  get 'adm_dashboard/index'

  post 'usuarios/encontrar'
  get 'usuarios/encontrar'

  post 'welcome/redirecionarusuario'
  
  get 'caronas/encontrarcaronas'
  post 'usuarios/toogleusuario'

  resources :campus
  resources :usuarios
  resources :caronas


  resources :caronas do
    member do
      get :encontrarcaronas
    end
  end
  
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/partials/_sidebar.html.erb
  <div class="container-fluid sidebar-dashboard p-0 m-0">
                    <ul class=" row sidebar-dashboard nav h-100 flex-column">
                        <li class="nav-item py-3">
                            <a class="nav-link active bg-transparent" aria-current="page" href="<%= user_dashboard_index_path%>">
                            <%= image_tag "icon_home", height: '44', width: '44' %>
                            <span class="px-3 h5 text-primary bg-transparent">Dashboard</span>
                            </a>
                        </li>
                        <li class="nav-item py-3">
                            <a class="nav-link bg-transparent" href="<%= caronas_path%>">
                            <%= image_tag "icon_minhascaronas", height: '44', width: '44' %>
                            <span class="px-3 h5 text-primary bg-transparent">Caronas</span>
                            </a>
                        </li>
                        <li class="nav-item py-3">
                            <a class="nav-link bg-transparent text-light" href="<%= caronas_path(usuario: current_user.iduff)%>">
                                <%= image_tag "icon_carona", height: '44', width: '44' %>
                            <span class="px-1 h5 text-primary bg-transparent">Minhas caronas</span>
                            </a>
                        </li>
                        <% if can? :manage, campus_path && usuarios_path%>
                            <li class="nav-item py-3 ">
                                <a class="nav-link bg-transparent " href="<%= campus_path%>">
                                <%= image_tag "icon_university", height: '44', width: '44' %>
                                <span class="px-3 h5 text-primary bg-transparent">Campus</span>
                                </a>
                            </li>

                          <li class="nav-item sidebar py-3">
                            <a class="nav-link bg-transparent" href="<%= usuarios_path	%>">
                            <%= image_tag "icon_user", height: '44', width: '44' %>
                            <span class="px-3 h5 text-primary bg-transparent">Usuários</span>
                            </a>
                         </li>
                        <% end %>
                    </ul>
  </div>