config/routes.rb
Rails.application.routes.draw do
  get 'user_dashboard/index'
  get 'adm_dashboard/index'

  post 'usuarios/encontrar'
  get 'usuarios/encontrar'

  post 'welcome/redirecionarusuario'
  
  get 'caronas/encontrarcaronas'
  post 'usuarios/toogleusuario'

  resources :campus
  resources :usuarios
  resources :caronas


  resources :caronas do
    member do
      get :encontrarcaronas
    end
  end
  
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/carona.rb
class Carona < ApplicationRecord
  belongs_to :usuario
  has_many :paradas, inverse_of: :carona
  accepts_nested_attributes_for :paradas, allow_destroy: true 

  #Validacao de carona para sempre ter ou uma partida ou destino para a UFF
  validate :validar_partida_destino

  def validar_partida_destino
    unless Campu.all.pluck(:nome).include?(partida) || Campu.all.pluck(:nome).include?(destino)
      errors.add(:partida, "deve ser um dos campus")
      errors.add(:destino, "deve ser um dos campus")
    end
  end

  validates :valor, numericality: { greater_than: 0, less_than: 1000 }
  validates :observacao, length: {maximum: 255}, allow_blank: true
  validates :destino, presence: :true, length: {minimum:3, maximum:55}
  validates :partida, presence: :true, length: {minimum:3, maximum:55}
  validates :passageiros, numericality: {greater_than:0, less_than: 5}
end

app/controllers/caronas_controller.rb
class CaronasController < ApplicationController
  authenticate_with_iduff_keycloak
  load_and_authorize_resource

  before_action :set_carona, only: %i[ show edit update destroy ]

  # GET /caronas or /caronas.json
  def index
    if params[:usuario].present?
      usuario_id = Pub::IdentificacaoLogin.find_by(iduff: params[:usuario]).id
      carona_usuario = Usuario.find(usuario_id)
      @caronas = carona_usuario.caronas.order(quando: :desc).all
    else
      @caronas = Carona.order(quando: :desc).all
    end 


  end

  # GET /caronas/1 or /caronas/1.json
  def show
  end

  # GET /caronas/encontrar
  # POST /caronas/encontrar
  def encontrarcaronas
    if params[:bairro].present?
      carona_por_nome = Carona.where("partida LIKE ? OR destino LIKE ?","%#{params[:bairro]}%","%#{params[:bairro]}%")                            
      render json: carona_por_nome.map{|v| v.serializable_hash(only: [:id, :partida, :destino])}
      
    else
      render json: []
    end
  end

  

  # GET /caronas/new
  def new
    @carona = Carona.new()
    @campus = Campu.all
  end

  # GET /caronas/1/edit
  def edit
    @campus = Campu.all
  end

  # POST /caronas or /caronas.json
  def create
    @carona = Carona.new(carona_params)    
    @carona.usuario_id = encontrar_id_current_user

    respond_to do |format|
      if @carona.save
        format.html { redirect_to carona_url(@carona), notice: "Carona was successfully created." }
        format.json { render :show, status: :created, location: @carona }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @carona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /caronas/1 or /caronas/1.json
  def update
      respond_to do |format|
        if @carona.update(carona_params)
          format.html { redirect_to carona_url(@carona), notice: "Carona was successfully updated." }
          format.json { render :show, status: :ok, location: @carona }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @carona.errors, status: :unprocessable_entity }
        end
      end
      @campus = Campu.all
  end

  # DELETE /caronas/1 or /caronas/1.json
  def destroy
    @carona.destroy

    respond_to do |format|
      format.html { redirect_to caronas_url, notice: "Carona was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carona
      @carona = Carona.find(params[:id])
    end

    #Encontrar o id do usuario atual e retorna o id deste usuario
    def encontrar_id_current_user 
      Pub::IdentificacaoLogin.where("iduff LIKE ?", "%#{current_user.iduff}%").pluck(:id).first
    end
    #Verificar se corrida é do usuario logado
    
    # Only allow a list of trusted parameters through.
    def carona_params
      params.require(:carona).permit(:quando, :valor, :passageiros, :observacao, :partida, :destino, :usuario_id, paradas_attributes:[:id, :paradas])
    end
end

app/helpers/caronas_helper.rb
module CaronasHelper
    def carona_pertence_ao_usuario?
        carona_usuario = Carona.find(params[:id]).usuario
        carona_usuario.creator.iduff == current_user.iduff
    end
end

app/views/caronas/_form.html.erb
<p id="notice"><%= notice %></p>
<%= form_with(model: carona, local: true, class:"p-3") do |form| %>
  <% if carona.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(carona.errors.count, "error") %> prohibited this carona from being saved:</h2>

      <ul>
        <% carona.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="d-flex justify-content-around">
    <div class="form-row w-50">
      <div class="form-group">
        <%= form.label :partida, class:"form-label h5" %>
        <%= form.text_field :partida, class:"form-control h5 partida" %>
      </div>
        <div class="h5 text-center text-primary click"><u>+ Adicionar Campus</u></div>
        <ul class="flex-wrap list-unstyled d-flex d-none campus-lista">
          <% @campus.each do |campi|%>
            <li class="p-2 bg-primary m-2 rounded text-light h6 nome-campus-partida"><%= campi.nome%></li>
          <%end%>
        </ul>

      <div class="links">
        <div id="experiences" class="form-group my-2">
          <%= form.fields_for :paradas do |parada| %>
            <%= render 'parada_fields', f: parada %>
          <% end %>
        </div>
        <%= link_to_add_association 'adicionar parada', form, :paradas, class:"btn btn-primary my-3"%>
      </div>
      <div class="form-group">
        <%= form.label :destino, class:"form-label h5" %>
        <%= form.text_field :destino, class:"form-control h5 destino" %>
      </div>
      <div class="h5 text-center text-primary click"><u>+ Adicionar Campus</u></div>
        <ul class="flex-wrap list-unstyled d-flex d-none campus-lista">
          <% @campus.each do |campi|%>
            <li class="p-2 bg-primary m-2 rounded text-light h6 nome-campus-destino"><%= campi.nome%></li>
          <%end%>
        </ul>
    </div>
  
    <div class="form-row w-50 mx-3">
      <div class="form-group p-2 row">
        <%= form.label :quando, class:"form-label h5"%>
        <%= form.datetime_select(:quando, start_year: Time.now().year, :prompt => {day: "Dia", month: 'Mês', year: 'Ano', hour:"horas", minute:'minutos'}, :with_css_classes => {day: 'form-select w-25 mx-2', month: 'form-select w-25 mx-2', year: 'form-select w-25 mx-2', hour:"form-select w-25 m-2", minute:'form-select w-25 m-2'})%>
      </div>

      <div class="form-group p-2">
        <%= form.label :valor, class:"form-label h5" %>
        <%= form.number_field :valor, value: @carona.valor ? '%.2f' % @carona.valor : nil, min: 0, class: "form-control valor", step: 0.01 %>
      </div>
  
      <div class="form-group p-2">
        <%= form.label :passageiros, class:"form-label h5" %>
        <%= form.number_field :passageiros, class:"form-control h5", min: 0, max: 5%>
      </div>

      <div class="form-group p-2">
        <%= form.label :observação, class:"form-label h5"%>
        <%= form.text_area :observacao, class:"form-control h5" %>
      </div>
    </div>
    
  </div>
   <div class="form-group my-5 d-flex justify-content-center">
    <%=  %>
    <%= form.submit("#{carona.destino.blank? ? "Criar Caronas" : "Editar Caronas"}", class:"btn btn-primary w-75")%>
  </div>
<% end %>

app/views/caronas/_parada_fields.html.erb
<div class="nested-fields">
    <div class="form-group d-flex align-items-center py-2">
        <%= f.label :paradas, class:"form-label h5 mx-2"%>
        <%= f.text_field :paradas, class:"form-control h5 mx-2" %> 
        <%= link_to_remove_association '-', f, class:"btn btn-danger"%>   
    </div>
</div>

app/views/caronas/edit.html.erb
        <h1 class="py-2">Editar Carona</h1>

        <%= render 'form', carona: @carona %>

<%= link_to 'Mostrar Carona', @carona, class: "btn btn-primary"%> |
<%= link_to 'Retornar', caronas_path, class: "btn btn-primary" %>

</section>

app/views/caronas/index.html.erb
<main class="d-flex sidebar justify-content-between">
  <%= render "partials/sidebar" %>
  <section class="conatiner m-3 overflow-auto p-3">
                          
    <div class="d-flex justify-content-between align-items-center">
      <h1 class="py-3">Caronas</h1>
      <%= link_to 'Oferecer Carona', new_carona_path, class:"btn btn-success text-light"%>
    </div>
   
    <%= select_tag  :nome, 
                    options_for_select(@caronas.collect{|v| [v.partida, v.id]}), 
                    class:"form-select select2-caronas ",
                    include_blank: true,
                    size:10
    %>




    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col" class="h5 p-3 text-center">Quando</th>
          <th scope="col" class="h5 p-3 text-center">Valor</th>
          <th scope="col" class="h5 p-3 text-center">Passageiros</th>
          <th scope="col" class="h5 p-3 text-center">Partida</th>
          <th scope="col" class="h5 p-3 text-center">Destino</th>
          <th scope="col" class="h5 p-3 text-center">Usuário</th>
          <th scope="col" colspan="3" class="h5 p-3 text-center">Editar</th>
        </tr>
      </thead>

      <tbody>
        <% @caronas.each do |carona| %>
          <tr scope="row">
            <td class="text-center p-3"><%= carona.quando.day %>/<%= carona.quando.month %>/<%= carona.quando.year %> - <%= carona.quando.hour %>:<%= carona.quando.min %></td>
            <td class="text-center p-3">R$ <%= carona.valor %></td>
            <td class="text-center p-3"><%= carona.passageiros %></td>
            <td class="text-center p-3"><%= carona.partida %></td>
            <td class="text-center p-3"><%= carona.destino %></td>
            <td class="text-center p-3"><%= carona.usuario.creator.nome %></td>
            <td class="text-center p-3"><%= link_to 'Carona', carona, class:"btn btn-primary text-light"%></td>
            <% if usuario_is_admin? || params[:usuario].present? %>
              <td class="text-center p-3"><%= link_to 'Editar', edit_carona_path(carona), class:"btn btn-warning text-light" %></td>
              <td class="text-center p-3"><%= link_to 'Apagar', carona, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger text-light" %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>


  </section>
</main>

app/views/caronas/new.html.erb
<section class="p-2">
    <a href=<%= caronas_path %> title="Retornar para <%= caronas_path%>" class="btn btn-info rounded-circle p-0">
        <%= image_tag "icon_seta_voltar", height: '44', width: '44' %>
    </a>
    <main class="p-2">
        <h1>Nova Carona</h1>

        <%= render 'form', carona: @carona %>
        
    </main>
</section>

app/views/caronas/show.html.erb
<p id="notice"><%= notice %></p>
<main class="d-flex sidebar justify-content-between">
  <%= render "partials/sidebar" %>

  <section class="m-3 w-75 container">
      <div class="row mb-5 px-2">
        <%= image_tag "imagem_da_carona", class:"w-25"%>

        <div class="col">
          <h5 class="py-2"><strong>Destino:</strong> <%= @carona.partida%></h5>
          <h5 class="py-2"><strong>Partida:</strong> <%= @carona.destino%></h5>
          <h5 class="py-2"><strong>Passageiros:</strong> <%= @carona.passageiros%></h5>
          <h5 class="py-2"><strong>Valor:</strong> <%= @carona.valor%></h5>
          <h5><strong>Paradas:</strong> 
            <ul class="py-2 list-unstyled">
              <% if @carona.paradas.size > 0%>
                <% @carona.paradas.each_with_index do |parada, index|%>
                 <li class="h5 px-3"><%= "#{index + 1}° Parada ->"%> <%= parada.paradas%></li>
                <% end %>
              <% else %>
                <li class="h5 px-3"><%= "Sem paradas"%></li>
              <%end%>
            </ul>
          </h5>
          <h5><strong>Quando:</strong> <%= @carona.quando.strftime("%d/%m/%Y - %H: %M")%></h5>
          <h5 class="py-2"><strong>Observação:</strong> <%= @carona.observacao%></h5>
        </div>
      </div>
      <div class="d-flex justify-content-center">
        <% if usuario_is_admin? || carona_pertence_ao_usuario? %>
          <%= link_to 'Editar Carona', edit_carona_path(@carona), class: "btn btn-warning text-light m-2" %>
        <% end %>
        <%= link_to 'Retornar', caronas_path, class:"btn btn-info text-light m-2" %>
      </div>
 
  </section>
</main>