config/routes.rb
Rails.application.routes.draw do
  get 'user_dashboard/index'
  get 'adm_dashboard/index'

  post 'usuarios/encontrar'
  get 'usuarios/encontrar'

  post 'welcome/redirecionarusuario'
  
  get 'caronas/encontrarcaronas'
  post 'usuarios/toogleusuario'

  resources :campus
  resources :usuarios
  resources :caronas


  resources :caronas do
    member do
      get :encontrarcaronas
    end
  end
  
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/usuario.rb
class Usuario < ApplicationRecord


    belongs_to :creator, class_name: "Pub::IdentificacaoLogin", foreign_key: "creator_id"
    has_many :caronas
    
    validates_associated :creator,:message => "Nome não deve estar vazio", :if => Proc.new {|usuario|usuario.creator.nome.blank?}
    validates_associated :creator,:message => "IDUFF não deve estar vazio", :if => Proc.new {|usuario|usuario.creator.iduff.blank?}
    
    validates_with UsuarioValidacao


    def toogle_data_desativacao
        if self.data_desativacao.nil?
            self.data_desativacao = Time.now()
        else
            self.data_desativacao = nil
        end
    end

    



    def encontrar_iduff(iduff)
        Pub::IdentificacaoLogin.find_by(iduff: iduff).present?
    end
    
    private 
        

end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  authenticate_with_iduff_keycloak
  load_and_authorize_resource
  before_action :set_usuario, only: %i[ show edit update destroy ]

  # GET /usuarios or /usuarios.json
  def index
    @usuarios = Usuario.all
    @nomes_finder = Pub::IdentificacaoLogin.all

  end

  # GET /usuarios/1 or /usuarios/1.json
  def show
        
  end
  
  # GET /usuarios/encontrar
  # POST /usuarios/encontrar
  def encontrar
    if params[:usuario].present?
      ids_usuarios_encontrados = Pub::IdentificacaoLogin.where("nome LIKE ? OR iduff LIKE ?","%#{params[:usuario]}%","%#{params[:usuario]}%").pluck(:id)                
      usuarios_encontrados = Usuario.where(creator_id: ids_usuarios_encontrados)                              
      
      render json: usuarios_encontrados.map{|v| v.serializable_hash(include: {creator: {only: [:iduff,:nome]}}, only: :id)}
    else 
      render json: []
    end
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # post /usuarios/toogleusuario
  def toogleusuario
    if params[:id].present?
      usuario_toogle = Usuario.find(params[:id])
      usuario_toogle.toogle_data_desativacao
      usuario_toogle.save!

      respond_to do |format|
        if usuario_toogle.data_desativacao.nil?
          format.html {redirect_to usuarios_path, notice: "Usuario #{usuario_toogle.creator.nome} foi desativado" }
        else
          format.html {redirect_to usuarios_path, notice: "Usuario #{usuario_toogle.creator.nome} foi ativado" }
        end
      end
    end

    
    
  end

  # GET /usuarios/1/edit
  def edit
    @usario_creator = @usuario.creator
  end

  # POST /usuarios or /usuarios.json
  def create
    @usuario = salvar_usuario
    
    respond_to do |format|
      if @usuario.save       
        format.html { redirect_to usuario_url(@usuario), notice: "Usuario was successfully created." }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1 or /usuarios/1.json
  def update
    respond_to do |format|

      if @usuario.update(usuario_params) 
        format.html { redirect_to usuario_url(@usuario), notice: "Usuario was successfully updated." }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1 or /usuarios/1.json
  def destroy
    @usuario.destroy
    @usuario.creator.destroy

    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: "Usuario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def usuario_params
      params.require(:usuario).permit(:admin, :nome, :iduff, :data_desativacao)
    end
    
    def encontrar_usuario
      if params[:nome].present? && !params[:nome].nil?
        nomes_encontrados = Pub::IdentificacaoLogin.where("nome LIKE ?", "%#{params[:nome]}%").pluck(:id)                
        usuarios = Usuario.where(creator_id: nomes_encontrados)
        usuarios.all        
      else
        Usuario.all      
      end      
            
    end

    def salvar_usuario
        usuario = Usuario.new()
        usuario.admin = params[:usuario][:admin]
        usuario.creator = Pub::IdentificacaoLogin.new(iduff: params[:creator][:iduff], nome: params[:creator][:nome])
        usuario.data_desativacao = params[:usuario][:data_desativacao]
        usuario
    end

end

app/helpers/usuarios_helper.rb
module UsuariosHelper
    def usuario_desativado(atributo)
        return "bg-secondary text-white" unless atributo.nil?
    end

    def usuario_nome_botao(atributo)
        atributo.nil? ? "Desativar usuario" : "Ativar usuario"
    end

    def usuario_verificar_data_desativacao(atributo)
        atributo.nil? ? "Ativo" : "Desativado"
    end

    def usuario_is_admin(atributo)
        atributo ? "Administrador" : "Usuário"
    end

    def usuario_iduff_mask(atributo)
        "#{atributo[0..2]}.#{atributo[3..5]}.#{atributo[6..8]}-#{atributo[9..10]}"
    end
end

app/views/usuarios/_form.html.erb
<%= form_with(model: @usuario, local: true, class:"px-3") do |form| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
        <% @usuario.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <div class="form-group ">
      <%= form.label :admin , class: "form-check-label h5"%>
      <%= form.check_box :admin , class: "form-check-input h6"%>
    </div>

    <div class="form-group col-md-6">
      <%= fields_for :creator, @usuario.creator do |creator_detail_form| %>

        <div class="form-group my-3 ">
          <%= creator_detail_form.label :nome, class:"form-label h5"%>
          <%= creator_detail_form.text_field :nome, class: "form-control"%>
        </div>  

        <div class="form-group my-3">
          <%= creator_detail_form.label :iduff, class:"form-label h5" %>
          <%= creator_detail_form.text_field :iduff, class: "form-control cpf"%>
        </div>       
        
      <%end%>
    </div>

  <div class="actions d-flex justify-content-center align-items-center mt-5">
    <%= form.submit class: "btn btn-primary text-light mx-2"%>
    <%= link_to t("Back"), usuarios_path , class: "btn btn-info text-light mx-2"%>

  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form'%>

<%= link_to t('Show'), @usuario %> |
<%= link_to t('Back'), usuarios_path %>

app/views/usuarios/index.html.erb
<p id="notice" ><%= notice %></p>
<main class="d-flex sidebar justify-content-between">
  <%= render "partials/sidebar" %>
  <section class="conatiner m-3 w-75">
    



<div class="d-flex justify-content-between align-items-center">
  <h1>Usuários</h1> 
  <%= link_to 'Cadastrar novo Usuário', new_usuario_path, class: "btn btn btn-success text-light" %>
</div>

<%= select_tag  :nome, 
                options_for_select(@usuarios.collect{|u| [u.creator.iduff+"-"+u.creator.nome,u.creator.nome]}), 
                class:"input-group select2-usuarios",
                include_blank: true,
                data:{source: usuarios_path, remote: true},
                size:10
%>
<br>

</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col" class="h5 p-3 text-center">#</th>
      <th scope="col" class="h5 p-3 text-center">Nome</th>
      <th scope="col" class="h5 p-3 text-center">Iduff</th>
      <th scope="col" class="h5 p-3 text-center">Data de Desativacao</th>
      <th scope="col" class="h5 p-3 text-center">Admin</th>
      <th scope="col" class="h5 p-3 text-center">Editar</th>
    </tr>
  </thead>

  <tbody>
  <% @usuarios.each do |usuario| %>
    <tr class="<%= usuario_desativado(usuario.data_desativacao)%>" scope="row">
      <td class="text-center p-3"><%= usuario.id%></td>
      <td class="text-center p-3"><%= usuario.creator.nome%></td>
      <td class="text-center p-3"><%= usuario.creator.iduff%></td>
      <td class="text-center p-3"><span class="h6 text-bold py-2"><%= usuario.data_desativacao%><span><%= button_to usuario_nome_botao(usuario.data_desativacao), usuarios_toogleusuario_path,
      params:{id:usuario.id}, class:"btn #{ usuario.data_desativacao.nil? ? "bg-danger" : "bg-success"} text-light" %></td>
      <td class="text-center p-2"><%= image_tag "icon_usuario", width: 24, heigth: 24 %><br><span class="my-2"><%= usuario.admin ? "Administrador" : "Usuario" %></span></td>
      <td class="text-center p-3"><%= link_to 'Mostrar', usuario, class:"btn btn-primary text-white" %></td>
      <td class="text-center p-3"><%= link_to 'Editar', edit_usuario_path(usuario), class:"btn btn-warning text-white" %></td>
      <td class="text-center p-3"><%= link_to 'Apagar', usuario, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger text-white" %></td>
    <tr>
  <% end %>
  </tbody>
</table>

  </section>

</main>

app/views/usuarios/new.html.erb
<h1 class="p-2">Cadastrar Novo Usuário</h1>

<%= render 'form', usuario: @usuario %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>
<main class="d-flex sidebar justify-content-between">
  <%= render "partials/sidebar" %>

  <section class="m-3 w-75 container">
    <div class="w-100 col d-flex align-items-center jus"> 
      <div class="d-flex w-25 flex-wrap justify-content-center align-items-center">
        <%= image_tag "imagem_aluno", heigth: 125, width: 125, class:"mb-3" %>
        <%= link_to 'Editar Dados', edit_usuario_path(@usuario), class: "btn btn-warning text-light m-2"%>
        <%= link_to 'Retornar', usuarios_path, class: "btn btn-info text-light" %>
      </div>
      <div class="mx-5 w-50">
        <h6 class="my-3"><strong>Nome: </strong><%= @usuario.creator.nome%></h6>
        <h6 class="my-3"><strong>iduff: </strong><%= usuario_iduff_mask(@usuario.creator.iduff)%></strong></h6>
        <h6 class="my-3"><strong>Papel: </strong><%= usuario_is_admin(@usuario.admin)%></strong></h6>
        <h6 class="my-3"><strong>Ativo: </strong><%= usuario_verificar_data_desativacao(@usuario.data_desativacao)%> <%= @usuario.data_desativacao%></strong></h6>  
      </div>
      
      
    </div>
    <div class="w-100 row p-3 my-4">
      <h5>Caronas de <%= @usuario.creator.nome %></h5>
      <% if @usuario.caronas.size > 0%>
        <ul class="list-group my-4 w-100">
          <% @usuario.caronas.each do |carona|%>
            <li class="list-group-item p-3 d-flex justify-content-between">
              <div>
                <p class="h5"><strong>Destino: </strong><%= carona.destino%></p>
                <p class="h5"><strong>Partida: </strong><%= carona.partida%></p>
                <p class="h5"><strong>Paradas:  </strong>
                  <% if carona.paradas.size > 0%>
                      <% carona.paradas.each do |parada|%>
                        <%=" "+parada.paradas+" "%>
                      <% end %>
                  <% else %>
                    <%= "Sem paradas"%>
                <%end%>
                <p class="h5"><strong>Passageiros: </strong><%= carona.passageiros%></p>
                <p class="h5"><strong>Valor: </strong><%= carona.valor%></p>
                <p class="h5"><strong>Data: </strong><%= carona.quando.strftime('%d/%m/%Y - %H:%M')%></p>

              </div>
              <div>
              <%= link_to "Ver Carona", "/caronas/#{carona.id}", class:"btn btn-primary text-light"%>
              </div>
            </li>
            
          <%end%>
        </ul>
        <% else %>
        <p class="h6">Usuario não possui corridas no momento</p>
      <% end %>
    </div>

  </section>
</main>